### ISSUE TITLE
Scene passed in renderingCallback is not initialized

### ISSUE THREAD

**Issue by fpatzelt** [ubi-agni/mujoco_ros_pkgs#17]
I noticed that the rendering of contact surfaces stopped working. The scene passed to the renderCallback has a geom buffer with size 0 ([scene->maxgeom = 0](https://github.com/ubi-agni/mujoco_contact_surfaces/blob/f99bbe7160dd30a83f956c94ac593ebb2c155598/src/mujoco_contact_surfaces_plugin.cpp#L925)). 
Either [mjv_makeScene](https://github.com/ubi-agni/mujoco_ros_pkgs/blob/23073fe9a078538681152a9fdc44b71569c6b8e0/mujoco_ros/src/mujoco_env.cpp#L218) is never called or a different scene is passed to the [renderCallback](https://github.com/ubi-agni/mujoco_ros_pkgs/blob/23073fe9a078538681152a9fdc44b71569c6b8e0/mujoco_ros/src/mujoco_env.cpp#L278).

**Comment by DavidPL1** [comment]
The problem was that the environment just used its own scene for the plugin render callbacks, which is only initialized when cameras are defined in the scene and offscreen rendering is turned on. The result would also only have been visible in the rendered camera images, not the simulation GUI.
This is fixed in 7158fc0, i.e. the GUI rendering now passes the scene used to render the GUI frame.

I was wondering if we should include the option to let the plugins also render to offscreen scenes, because if you run the server headless the render callbacks currently don't get called.
Example use case: recording a video with e.g. contact surface visualization on a headless setup for demonstration purposes.

On the other hand this could interfere with cameras used as data processing sources, so we should use a user parameter in the model xml to flag cameras that are only used for visualization and only run callbacks for them.

@rhaschke, what's your take on this?

**Comment by rhaschke** [comment]
I don't fully understand the problem yet. Let's talk tomorrow in person.
