### ISSUE TITLE
ROS 2 Version Availability 

### ISSUE THREAD

**Issue by Ekanshh** [ubi-agni/mujoco_ros_pkgs#37]
Hi,

In the documentation, I noticed that adaptations for ROS 2 (Humble) are in progress. Could you share an estimated timeline for when the ROS 2 version of this package will be available? This information would be very helpful for my project planning.

Thanks in advance! :beers:

**Comment by DavidPL1** [comment]
Yes, we decided to add the option to build the simulation with ROS 2 already some time ago. But due to other deadlines I always had to postpone getting familiar with the differences imposed by using ROS 2 and coming up with a flexible design to keep most of the codebase independent from the ROS version. I did start to cleanup some code for a cleaner separation of ROS and core simulation code, but there hasn't been done much more.
However, recently a lab from another university in Germany reached out to discuss collaborating on this matter. I can not promise you anything but I hope to have a basic working prototype by the end of the year. If we get the collaboration going, we might get some results earlier.

I'll keep you posted.

**Comment by Ekanshh** [comment]
Thanks for your reply, @DavidPL1!

It’s good to hear that there’s ongoing work to make the repo more flexible and ROS 2 compatible. To add, I’m genuinely impressed by this repository—it’s hands down the best I’ve found for integrating ROS with MuJoCo, and the plugin-based interface is a fantastic approach. Thanks so much for all the effort you've put into it already! The potential collaboration sounds exciting too, as it could really help lighten your development load. 

One suggestion: it might be helpful for new contributors like me if you could create a few  "good first issues" with some task descriptions. This way, we can jump in right away and, hopefully, speed things up on a few fronts.

Thanks again! I’ll go ahead and close this issue now. 😊

**Comment by DavidPL1** [comment]
Thank you for your kind words and appreciation of this project.
I'll try to workout features that might be a good start for first-time contributors, that's a good idea

**Comment by DavidPL1** [comment]
Good news: I've been working on porting the core library to ROS 2 (Humble) in the past week and just now reached the state of a minimal working prototype with most of the previous features available in the ROS 2 version. This prototype resides in [this branch](https://github.com/ubi-agni/mujoco_ros_pkgs/tree/wip-ros-humble), details about the current state of development can be found in the commit message.

There are a few things to note, though:
- In the wip branch both ROS 1 and ROS 2 versions can be built. Make sure though not to mix ROS versions in your workspace (my workflow consists of having dedicated humble and one workspaces and soft-linking the root directory into each respective src dir and keeping separate terminals for building and running for each).
- Though using catkin as ROS 1 buildtool still supports develspace builds, using the develspace is not recommended from this point on since there is a name clash in the launch directory (both versions have a launchfile called `launch_server.launch`).
- For now I'm focusing on the core library, plugins will follow later (however, @tenfoldpaper is already working on a port of the control plugin in [this fork](https://github.com/tenfoldpaper/mujoco_ros_pkgs))
- Tests for the ROS 2 build have yet to be implemented. I have been testing things manually, but there is no guarantee everything works as intended. It's a work in progress, after all.
- If you play around with the initial version and encounter bugs or notice missing features **that are not yet listed in the commit message**, leave a short description here or open a new issue.
- I'll continue working on this probably mid January.

Merry Christmas!
