### ISSUE TITLE
mujoco_ros_plugin_test.cpp:109 is flaky

### ISSUE THREAD

**Issue by rhaschke** [ubi-agni/mujoco_ros_pkgs#40]
failing: https://github.com/ubi-agni/mujoco_ros_pkgs/actions/runs/11912774801/job/33197093429
passing: https://github.com/ubi-agni/mujoco_ros_pkgs/actions/runs/11912774801/job/33197395247
(same run/commit)

**Comment by DavidPL1** [comment]
I've already noticed. Not quite sure why.

The test calls the step function with default arguments:
https://github.com/ubi-agni/mujoco_ros_pkgs/blob/4efd1c01d183d5f0a2452c75e11e364c67e5719b/mujoco_ros/src/mujoco_env.cpp#L736C3-L768C2

and stepping happens here:
https://github.com/ubi-agni/mujoco_ros_pkgs/blob/4efd1c01d183d5f0a2452c75e11e364c67e5719b/mujoco_ros/src/physics.cpp#L100C3-L128C5

Since, `mj_step` internally triggers the callbacks, `ran_control_cb.store(true)` should have been set long before decrementing the requested step counter in the physics loop. This is then the signal to unblock the step function, but still sometimes the atomic is not set when leaving the step function.

My best guess is that due to compiler optimization the access of the atomic in the test happens before the actual write in the plugin, they run in separate threads after all.
This can probably circumvented by waiting a short time before testing the atomic, code-wise I have no better idea how to fix this.

**Comment by DavidPL1** [comment]
Found the issue: looking into mujoco I found that mjcb_control is called in [mj_forward](https://github.com/google-deepmind/mujoco/blob/5c23ae11efc58653ec836caf8755239d2d37c04b/src/engine/engine_forward.c#L1045), i.e. when the simulation is paused. Thus actually the initial assumption of `ran_control` to be false causes the test to fail when the test is slower than the first paused step.
